# Generated by Django 2.1.1 on 2018-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogstagram_app', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
