# Generated by Django 2.1.1 on 2018-09-28 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogstagram_app', '0003_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_comment', to='dogstagram_app.User')),
            ],
        ),
    ]
